--select all machines in a trace
SELECT * FROM MACHINE_EVENTS 
	WHERE STARTTIME > 10000000
	AND   DURATION  > 5000 
	AND   STARTTIME < 15000000
	AND   MACHINE_ID in 
	(SELECT MACHINE_ID FROM MACHINES WHERE 
	TRACE_ID = 1);

--select all processes in a trace: 
SELECT * FROM PROCESS_EVENTS
	WHERE STARTTIME > 10000000
	AND   DURATION  > 5000 
	AND   STARTTIME < 15000000
	AND PROCESS_ID IN (
	SELECT PROCESS_ID FROM PROCESSES WHERE
		MACHINE_ID IN 
			(SELECT MACHINE_ID FROM MACHINES WHERE 
			TRACE_ID = 1) 
	);

--select all threads in a trace.
SELECT * FROM THREAD_EVENTS
	WHERE STARTTIME > 10000000
	AND   DURATION  > 5000 
	AND   STARTTIME < 15000000
	AND   THREAD_ID IN
	(SELECT THREAD_ID FROM THREADS WHERE
		THREAD_ID IN
		(SELECT PROCESS_ID FROM PROCESSES WHERE
			MACHINE_ID IN 
				(SELECT MACHINE_ID FROM MACHINES WHERE 
				TRACE_ID = 1)));